name: CI on main
on:
  push:
    branches: [main]
    paths: "src/**"

jobs:
  run-tests:
  
    runs-on: ubuntu-latest
    
    steps:
      # Check out repo
      - uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

           # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install and configure Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Load cached venv if cache exists
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashfiles('**/poetry.lock') }}

      # Install dependencies if cache does not exist
      - name: Installer dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      # Install project dependencies
      - name: Install Poetry library
        run: poetry install --no-interaction

      # Run tests
      - name: Test with pytest
        run: poetry run pytest tests
